# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'crud.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pymysql


class Ui_MainWindow(object):
    def connection(self):
        con = pymysql.connect(
            db="dbpython",
            user="root",
            passwd="",
            host="localhost",
            port=3306,
            autocommit=True,
        )
        cur = con.cursor()
        if cur:
            self.messagebox("Koneksi", "Koneksi Berhasil")
        else:
            self.messagebox("Koneksi", "Koneksi Gagal")

    def messagebox(self, title, message):
        mess = QtWidgets.QMessageBox()
        mess.setWindowTitle(title)
        mess.setText(message)
        mess.setStandardButtons(QtWidgets.QMessageBox.Ok)
        mess.exec_()

    def save(self):
        firstname = self.inputFirstName.toPlainText()
        lastname = self.inputLastName.toPlainText()
        address = self.inputAddress.toPlainText()
        phone = self.inputPhone.toPlainText()
        insert = (firstname, lastname, address, phone)
        print(insert)
        con = pymysql.connect(
            db="dbpython",
            user="root",
            passwd="",
            host="localhost",
            port=3306,
            autocommit=True,
        )
        cur = con.cursor()
        sql = (
            "INSERT INTO dbpython(first_name, last_name, address, phone)"
            + "VALUES"
            + str(insert)
        )
        data = cur.execute(sql)
        if data:
            self.messagebox("SUKSES", "Data Barang Tersimpan")
        else:
            self.messagebox("GAGAL", "Data Barang Gagal Tersimpan")

    def Tampil(self):
        firstname = self.inputFirstName.toPlainText()
        con = pymysql.connect(
            db="dbpython",
            user="root",
            passwd="",
            host="localhost",
            port=3306,
            autocommit=True,
        )
        cursor = con.cursor()
        cursor.execute("SELECT * FROM dbpython WHERE first_name = %s", str(firstname))
        data = cursor.fetchall()
        if data:
            for tp in data:
                self.inputFirstName.setPlainText(str(tp[0]))
                self.inputLastName.setPlainText(str(tp[1]))
                self.inputAddress.setPlainText(str(tp[2]))
                self.inputPhone.setPlainText(str(tp[3]))
            self.messagebox("INFO", "Data Ada")
        else:
            self.messagebox("INFO", "Data Belum Ada")

    def update(self):
        firstname = self.inputFirstName.toPlainText()
        lastname = self.inputLastName.toPlainText()
        address = self.inputAddress.toPlainText()
        phone = self.inputPhone.toPlainText()
        con = pymysql.connect(
            db="dbpython",
            user="root",
            passwd="",
            host="localhost",
            port=3306,
            autocommit=True,
        )
        cur = con.cursor()
        sql = "UPDATE dbpython SET last_name = %s, address = %s, phone = %s WHERE first_name = %s"
        data = cur.execute(sql, (lastname, address, phone, firstname))
        if data:
            self.messagebox("SUKSES", "Data Barang Berhasil Diupdate")
        else:
            self.messagebox("GAGAL", sql)

    def delete(self):
        firstname = self.inputFirstName.toPlainText()
        con = pymysql.connect(
            db="dbpython",
            user="root",
            passwd="",
            host="localhost",
            port=3306,
            autocommit=True,
        )
        cur = con.cursor()
        sql = "DELETE FROM dbpython WHERE first_name=%s"
        data = cur.execute(sql, (firstname))
        if data:
            self.messagebox("SUSKES", "Data Berhasil Dihapus")
        else:
            self.messagebox("GAGAL", "Data Gagal Dihapus")

    def clear(self):
        firstname = self.inputFirstName.setPlainText("")
        lastname = self.inputLastName.setPlainText("")
        address = self.inputAddress.setPlainText("")
        phone = self.inputPhone.setPlainText("")

    def setupUi(self, MainWindow):
        self.connection()
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1113, 723)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(390, 40, 321, 101))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 170, 81, 19))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 220, 81, 19))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(60, 280, 81, 19))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(60, 500, 81, 19))
        self.label_5.setObjectName("label_5")
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(60, 570, 112, 34))
        self.saveButton.setObjectName("saveButton")
        self.saveButton.clicked.connect(self.save)
        self.updateButton = QtWidgets.QPushButton(self.centralwidget)
        self.updateButton.setGeometry(QtCore.QRect(210, 570, 112, 34))
        self.updateButton.setObjectName("updateButton")
        self.updateButton.clicked.connect(self.update)
        self.deleteButton = QtWidgets.QPushButton(self.centralwidget)
        self.deleteButton.setGeometry(QtCore.QRect(360, 570, 112, 34))
        self.deleteButton.setObjectName("deleteButton")
        self.deleteButton.clicked.connect(self.delete)
        self.clearButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearButton.setGeometry(QtCore.QRect(510, 570, 112, 34))
        self.clearButton.setObjectName("clearButton")
        self.clearButton.clicked.connect(self.clear)
        self.checkButton = QtWidgets.QPushButton(self.centralwidget)
        self.checkButton.setGeometry(QtCore.QRect(660, 570, 112, 34))
        self.checkButton.setObjectName("checkButton")
        self.checkButton.clicked.connect(self.Tampil)
        self.inputFirstName = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.inputFirstName.setGeometry(QtCore.QRect(200, 170, 800, 40))
        self.inputFirstName.setObjectName("inputFirstName")
        self.inputLastName = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.inputLastName.setGeometry(QtCore.QRect(200, 220, 800, 40))
        self.inputLastName.setObjectName("inputLastName")
        self.inputAddress = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.inputAddress.setGeometry(QtCore.QRect(200, 280, 800, 131))
        self.inputAddress.setObjectName("inputAddress")
        self.inputPhone = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.inputPhone.setGeometry(QtCore.QRect(200, 500, 800, 40))
        self.inputPhone.setObjectName("inputPhone")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1113, 31))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Praktikum CRUD"))
        self.label_2.setText(_translate("MainWindow", "First Name"))
        self.label_3.setText(_translate("MainWindow", "Last Name"))
        self.label_4.setText(_translate("MainWindow", "Address"))
        self.label_5.setText(_translate("MainWindow", "Phone"))
        self.saveButton.setText(_translate("MainWindow", "Save"))
        self.updateButton.setText(_translate("MainWindow", "Update"))
        self.deleteButton.setText(_translate("MainWindow", "Delete"))
        self.clearButton.setText(_translate("MainWindow", "Clear"))
        self.checkButton.setText(_translate("MainWindow", "Check"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
